apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: ClickHouse FlowDB
    uid: clickhouse-flowdb
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    editable: false
    jsonData:
      defaultDatabase: wanguard
      server: clickhouse
      port: 8123
      protocol: http
      username: wanguard
      tlsSkipVerify: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
